(defproblem problem servicioemergencia
	(
	(dron drone1)
	(brazo brazod_dron1)
	(brazo brazoi_dron1)
	(base base)
	(loc base)
	(loc loc1)
	(loc loc2)
	(loc loc3)
	(loc loc4)
	(loc loc5)
	(contenido comida)
	(contenido medicina)
	(contenedor carrier1)
	(contenedor carrier2)
	(contenedor carrier3)
	(loc-dron base drone1)
	(brazos-dron drone1 brazod_dron1)
	(libre-brazo drone1 brazod_dron1)
	(brazos-dron drone1 brazoi_dron1)
	(libre-brazo drone1 brazoi_dron1)
	(distintos brazod_dron1 brazoi_dron1)
	(loc-contenedor base carrier1)
	(capacidad-contenedor carrier1 0)
	(capacidad-maxima carrier1 30)
	(loc-contenedor base carrier2)
	(capacidad-contenedor carrier2 0)
	(capacidad-maxima carrier2 90)
	(loc-contenedor base carrier3)
	(capacidad-contenedor carrier3 0)
	(capacidad-maxima carrier3 100)
	(cajas-localizacion comida loc1 0)
	(cajas-localizacion medicina loc1 0)
	(necesita-cajas comida loc1 15)
	(necesita-cajas medicina loc1 35)
	(cajas-localizacion comida loc2 0)
	(cajas-localizacion medicina loc2 0)
	(necesita-cajas comida loc2 46)
	(necesita-cajas medicina loc2 4)
	(cajas-localizacion comida loc3 0)
	(cajas-localizacion medicina loc3 0)
	(necesita-cajas comida loc3 46)
	(necesita-cajas medicina loc3 4)
	(cajas-localizacion comida loc4 0)
	(cajas-localizacion medicina loc4 0)
	(necesita-cajas comida loc4 12)
	(necesita-cajas medicina loc4 38)
	(cajas-localizacion comida loc5 0)
	(cajas-localizacion medicina loc5 0)
	(necesita-cajas comida loc5 8)
	(necesita-cajas medicina loc5 42)
	(cajas-base medicina 123)
	(cajas-base comida 127)
	)
	(
	(enviar-todo drone1)
	)
)
