(define (domain servicio-emergencia)
    (:requirements :strips :typing :fluents)
    (:types localizacion caja persona dron brazo contenido contenedor)
    
    (:predicates
        (loc-contenedor ?l - localizacion ?cont - contenedor)
        (contenido-contenedor ?cont - contenedor ?c - caja )
        (loc-dron ?l - localizacion ?d - dron)
        (loc-caja ?l - localizacion ?c - caja)
        (loc-persona ?l - localizacion ?p - persona)
        (tiene-contenido ?p -persona ?co - contenido)
        (contiene ?c - caja ?co - contenido)
        (carga-brazo ?c - caja ?b -brazo)
        (carga-brazo-contenedor ?cont - contenedor ?b -brazo)
        (libre-brazo ?d - dron ?b - brazo)
        (caja-pendiente ?c - caja)
        (brazos-dron ?d - dron ?b - brazo)
        (base ?l - localizacion)
        (no-base ?l - localizacion)
    )
    (:functions
        (capacidad-contenedor ?cont - contenedor)
    )
    (:action mover
        :parameters (?desde - localizacion ?hasta - localizacion ?d - dron ?cont - contenedor)
        :precondition (and (loc-dron ?desde ?d)
                        (no-base ?hasta)
                        (> (capacidad-contenedor ?cont) 0))
        :effect (and (loc-dron ?hasta ?d)
                    (not (loc-dron ?desde ?d))
                )
    )
    
    (:action regresar
        :parameters (?desde - localizacion ?hasta - localizacion ?d - dron ?cont - contenedor)
        :precondition (and (loc-dron ?desde ?d)
                        (base ?hasta)
                        (= (capacidad-contenedor ?cont) 0))
        :effect (and (loc-dron ?hasta ?d)
                    (not (loc-dron ?desde ?d))
                )
    )
    

    (:action coger-contenedor
        :parameters (?l - localizacion ?d - dron ?bi ?bd - brazo ?cont - contenedor)
        :precondition (and (loc-dron ?l ?d) 
                        (loc-contenedor ?l ?cont)
                        (libre-brazo ?d ?bi) 
                        (libre-brazo ?d ?bd)
                        (brazos-dron ?d ?bi)
                        (brazos-dron ?d ?bd)
                    )
        :effect (and (carga-brazo-contenedor ?cont ?bi)
                    (carga-brazo-contenedor ?cont ?bd) 
                    (not (loc-contenedor ?l ?cont))
                    (not (libre-brazo ?d ?bi))
                    (not (libre-brazo ?d ?bd))
                )
    )
    
    (:action soltar-contenedor
        :parameters (?l - localizacion ?d - dron ?bi ?bd - brazo ?cont - contenedor)
        :precondition (and (loc-dron ?l ?d) 
                        (loc-contenedor ?l ?cont)
                        (carga-brazo-contenedor ?cont ?bi) 
                        (carga-brazo-contenedor ?cont ?bd)
                        (brazos-dron ?d ?bi)
                        (brazos-dron ?d ?bd)
                    )
        :effect (and (not(carga-brazo-contenedor ?cont ?bi))
                    (not(carga-brazo-contenedor ?cont ?bd)) 
                    (loc-contenedor ?l ?cont)
                    (libre-brazo ?d ?bi)
                    (libre-brazo ?d ?bd)
                )
    )

    (:action cargar-contenedor
        :parameters (?cont - contenedor ?d - dron ?c - caja ?b - brazo ?l - localizacion)
        :precondition (and (loc-contenedor ?l ?cont) 
                    (loc-dron ?l ?d)
                    (carga-brazo ?c ?b)
                    (brazos-dron ?d ?b)
                    (< (capacidad-contenedor ?cont) 4))
        :effect (and (contenido-contenedor ?cont ?c)
                (not(carga-brazo ?c ?b))
                (libre-brazo ?d ?b)
                (increase (capacidad-contenedor ?cont) 1)
                )
    )
    
    (:action descargar-contenedor
        :parameters (?cont - contenedor ?d - dron ?c - caja ?b - brazo ?l - localizacion)
        :precondition (and (loc-contenedor ?l ?cont) 
                    (loc-dron ?l ?d)
                    (contenido-contenedor ?cont ?c)
                    (libre-brazo ?d ?b)
                    (brazos-dron ?d ?b)
                    (> (capacidad-contenedor ?cont) 0))
        :effect (and (not (contenido-contenedor ?cont ?c))
                (not (libre-brazo ?d ?b))
                (carga-brazo ?c ?b)
                (decrease (capacidad-contenedor ?cont) 1)
                )   
    )

    (:action dar-caja
        :parameters (?l - localizacion ?c - caja ?d - dron ?p - persona ?b - brazo ?co - contenido)
        :precondition (and (loc-dron ?l ?d) 
                        (brazos-dron ?d ?b) 
                        (carga-brazo ?c ?b) 
                        (contiene ?c ?co) 
                        (loc-persona ?l ?p)
                    )
        :effect (and (loc-caja ?l ?c) 
                    (not (carga-brazo ?c ?b)) 
                    (libre-brazo ?d ?b)
                    (tiene-contenido ?p ?co)
                    (not (caja-pendiente ?c))
                )
    )

    (:action coger-caja
        :parameters (?l - localizacion ?c - caja ?d - dron ?b - brazo)
        :precondition (and (loc-dron ?l ?d) 
                        (loc-caja ?l ?c) 
                        (libre-brazo ?d ?b) 
                        (brazos-dron ?d ?b)
                        (caja-pendiente ?c) 
                    )
        :effect (and (carga-brazo ?c ?b) 
                    (not (loc-caja ?l ?c))
                    (not (libre-brazo ?d ?b))
                )
    )
)